name: Autoupdate Branches

on:
  schedule:
   - cron: '*/5 * * * *' 

jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:      
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Update labeled brances
        shell: bash
        run: |
          for branch in $(gh pr list --label update-once-a-day --state open --draft) 
          do
          git checkout $branch
          git config pull.rebase false
          git config --global user.name 'autoupdate-bot'
          git config --global user.email 'autoupdate-bot@xxxl.digital'
          git pull origin master -X ours
          git push origin $branch
          done