name: autoupdate

on:
  pull_request_target:
    types:
      - opened
  workflow_dispatch:
  schedule:
   # - cron: '0 0 * * *' # Runs every day at midnight
    - cron: '*/5 * * * *' # Runs every day at midnight
  pull_request:
    types: [labeled]

jobs:
  autoupdate:
    name: auto_update_branch
    runs-on: ubuntu-latest
    permissions:
      contents: read


    if: contains(github.event.pull_request.labels.*.name, 'update-once-a-day')
    steps:
      - uses: actions/checkout@v4

      - name: Update branch
        run: git pull origin master

      - name: Push changes
        run: |
          git config --global user.name 'autoupdate-bot'
          git config --global user.email 'autoupdate-bot@xxx.digital'
          git push origin ${GITHUB_REF}

  comment:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: 'Comment PR'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'This is a test of a comment!!!'
            })
          