name: Autoupdate Branches

on:
  schedule:
   - cron: '*/5 * * * *' 
  pull_request:

jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:      
      - uses: actions/checkout@v4

      - name: Update labeled brances
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "primer hola mundo"
          branches=$(gh pr list --json headRefName --label "update-once-a-day" --state open);
          for branchName in $branches do
            echo "branchName $branchName.headRefName"
          done