# name: Autoupdate Branches

# on:
#   schedule:
#     - cron: '*/5 * * * *' 

# jobs:
#   autoupdate:
#     name: autoupdate
#     runs-on: ubuntu-latest
#     permissions:
#       contents: write
#       pull-requests: write

#     steps:      
#       - uses: actions/checkout@v4        
#         with:
#           fetch-depth: 0

#       - name: Update labeled brances
#         shell: bash
#         env:
#           GH_TOKEN: ${{ github.token }}
#         run: |
#           git config pull.rebase false
#           git config --global user.name 'autoupdate-bot'
#           git config --global user.email 'autoupdate-bot@xxxl.digital'
#           branches=$(gh pr list --json headRefName --label "update-once-a-day" --state open | jq '.[].headRefName');
#           for branchName in $branches; do
#             cleanBranchName=${branchName//\"/}
#             echo "Updating $cleanBranchName"
#             git checkout $cleanBranchName
#             git pull origin main -X ours
#             git push origin $cleanBranchName
#           done