name: Autoupdate Branches

on:
  schedule:
   - cron: '*/5 * * * *' 
  pull_request:

jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:      
      - uses: actions/checkout@v4

      - name: Update labeled brances
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "primer hola mundo"
          for branch in $(gh pr list); do
            echo "segundo hola mundo"
            echo "$branch"
            git checkout $branch
            git config pull.rebase false
            git config --global user.name 'autoupdate-bot'
            git config --global user.email 'autoupdate-bot@xxxl.digital'
            git pull origin master -X ours
            git push origin $branch
          done