name: Autoupdate Branches

on:
  schedule:
   - cron: '*/5 * * * *' 
  pull_request:

jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:      
      - uses: actions/checkout@v4

      - name: Update labeled brances
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "primer hola mundo"
          for prNumber in $(gh pr list --label "update-once-a-day" --draft); do
            echo "segundo hola mundo"
            echo "$prNumber"
            gh pr checkout $prNumber
            branchName="$(git rev-parse --abbrev-ref HEAD)"
            echo "branchName $branchName"
            git config pull.rebase false
            git config --global user.name 'autoupdate-bot'
            git config --global user.email 'autoupdate-bot@xxxl.digital'
            git pull origin main -X ours
            git push origin $branchName
          done