name: autoupdate

on:
  schedule:
   - cron: '*/5 * * * *' 

jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    if:  github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'update-once-a-day')
    steps:      
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Update branch
        run: |
          git checkout ${{steps.extract_branch.outputs.branch}}
          git config pull.rebase false
          git config --global user.name 'autoupdate-bot'
          git config --global user.email 'autoupdate-bot@xxxl.digital'
          git pull origin master -X ours

      - name: Push changes
        run: |
          git checkout  ${{steps.extract_branch.outputs.branch}}
          git config --global user.name 'autoupdate-bot'
          git config --global user.email 'autoupdate-bot@xxxl.digital'
          git push origin ${{steps.extract_branch.outputs.branch}}

  comment:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: 'Comment PR'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'This is a test of a comment!!!'
            })
          